version: '3.5'

services:
  lightfeather-managementsystem-express:
    image: lightfeather-managementsystem-express:latest
    ports: 
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile  
